import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ReduxProvider from "./ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme='dracula'>
      <ReduxProvider>
        <body className={inter.className + ''}>
          {/* <div className="w-2/12 h-screen border border-r">
            <Navbar />
          </div>
          <div className="w-10/12 h-screen overflow-y-scroll">
            {children}
          </div> */}
          <div className="drawer lg:drawer-open">
            <input id="my-drawer-2" type="checkbox" className="drawer-toggle" />
            <div className="drawer-content">
              {/* <label htmlFor="my-drawer-2" className="btn btn-primary drawer-button lg:hidden">Open drawer</label> */}
              <div className="lg:hidden navbar bg-base-300 rounded-b-2xl ">
                <div className="flex-none">
                  <label htmlFor="my-drawer-2" className="btn btn-square btn-ghost">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" className="inline-block w-5 h-5 stroke-current"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
                  </label>
                </div>
                <div className="flex w-full justify-center items-center">
                  <a className="btn btn-ghost text-xl">Kaushik Saha</a>
                </div>
                <div className="avatar pr-2">
                  <div className="w-12 rounded-full">
                    <img src="https://i.pinimg.com/originals/21/d0/16/21d016b1ca2a894be50ed09c00338439.jpg" />
                  </div>
                </div>
              </div>

              {children}


            </div>
            <div className="drawer-side overflow-hidden ">
              <label htmlFor="my-drawer-2" aria-label="close sidebar" className="drawer-overlay w-full"></label>
              <Navbar />

            </div>
          </div>
        </body>
      </ReduxProvider>
    </html>
  );
}
