import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ReduxProvider from "./ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={inter.className + ' flex w-full'}>
          <div className="w-2/12 h-screen border border-r">
            <Navbar />
          </div>
          <div className="w-10/12 h-screen overflow-y-scroll">
            {children}
          </div>
        </body>
      </ReduxProvider>
    </html>
  );
}
